server:
  port: 8090

debug: true

spring:
  datasource:
    #配置阿里巴巴数据源的四大件
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/edoc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      #配置连接池的详细信息
      initialSize: 1
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
  mvc:
    #指定从前台接收日期参数的格式
    date-format: yyyy-MM-dd

  #设置JSON日期序列化输出格式，北京时间相对伦敦有8个小时时差所以使用GMT+8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    #格式化输出json格式数据
    serialization:
      indent-output: true

#配置mybatis
mybatis:
  type-aliases-package: com.th.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
